### ISSUE TITLE
Detect previous instance: open file / sprite as a new tab in existing Aseprite session / window

### ISSUE THREAD

**Issue by Ashedragon** [aseprite/aseprite#477]
A setting that could be toggleable that would allow aseprite to use the instance already open to open the file rather than creating a new instance every time.  I'll elucidate:
Say I have .ase files set to open with aseprite.  I double-click one of them and it opens aseprite.  If I then double-click another file to open it, it would (instead of creating an entirely new instance of aseprite) simply open the file in the aseprite that currently exists.

![image](https://cloud.githubusercontent.com/assets/6158748/4104306/ca7a0824-3186-11e4-9551-bee501451ee0.png)

**Comment by dacap** [comment]
This feature is needed for the Steam release:

- when we double-click a .ase file, a new Aseprite.exe is launched
- if there is a Aseprite.exe running, we've to send a command to this instance to open the file, then we are done (we can close the second instance)
- if we are the first Aseprite.exe instance running, we check if we are installed on Steam, in that case we've to launch the appid and close this instance (so the app is initialized from Steam).
- the first running instance has to start in a "server" mode, so other instances can send commands to this instance (e.g. like open a file)

This IPC could be used to solve #533 too.

**Comment by dacap** [comment]
This can be solved on Windows using DDE. [This is an old technology](https://blogs.msdn.microsoft.com/oldnewthing/20130919-00/?p=3193), but it looks like Microsoft Office is still using it, so we can go for it.

Note: The Allegro port cannot handle DDE messages correctly, it looks like only the Skia port will be able to fix this issue. Anyway in the future, when we implement a full COM server, we can remove the DDE processing.

**Comment by dacap** [comment]
This fix will be available for first time in the beta branch of the Steam release. (It means, using the Skia branch + special registry keys to use DDE.)

**Comment by dacap** [comment]
I'm reopening this issue to add Linux support.

**Comment by daisyowl** [comment]
should this be working on windows now? i have png files associated with aseprite but they always open a new instance of aseprite when opened from the desktop or any other app

i'm on win10 / aseprite v1.2.9x64

**Comment by dacap** [comment]
This should be working on Windows too, did you use the installer or the portable version? did you associate the .aseprite file format with Aseprite manually?

**Comment by daisyowl** [comment]
i installed with the installer. now that i check, it opens .aseprite files in the same aseprite instance, but not .png files (which I bound to aseprite manually i think)

**Comment by dacap** [comment]
@daisyowl you can check the details of the #1070 issue to see how to associate other files as the .aseprite type

**Comment by daisyowl** [comment]
hmm, i followed the instructions here as best as i could understand and it still doesn't work (opening a .png from the windows explorer or in unity)

![regedit](https://user-images.githubusercontent.com/27868711/51294295-29ae8400-19c7-11e9-981f-302c1af6f30a.PNG)

**Comment by daisyowl** [comment]
ok so, update: after a bunch of fiddling, it will open from unity/file exlorer with my current setup, which is:

- having the registry entry for `.png` point to `AsepriteFile` as above
- ALSO setting the file explorer "open with" dialogue to aseprite

**Comment by daisyowl** [comment]
without the second step (file explorer dialog) it would keep opening them in new instances of aseprite

**Comment by agameraaron** [comment]
I am having this bug after a recent Aseprite update (currently v1.2.11-x64) in Linux Mint 19.1 XFCE (64-bit) and it's really messing with my workflow lately. I like to keep my file browser (Thunar 1.6.15) open in another window as I'm working with a lot of different sprites.

**Comment by MightyPrinny** [comment]
We need a hero for linux users for either this or drag and drop support.

**Comment by dacap** [comment]
Yeah, if someone want to contribute that would be great (the [clipboard part](https://github.com/dacap/clip) was already a lot of work just for the Linux port compared to Windows and macOS 😢)

**Comment by agameraaron** [comment]
Wow, you're so nice to us Linux users, dacap. I could swear you were already one of us 😅.
I had no clue you made a whole library for making a cross-platform clipboard in C++. Bravo!!
It's a wonder why it hasn't already been done before.

**Comment by henriquecolini** [comment]
Hey, sorry, but has there been any progress on this? As a game developer, opening image assets constantly is a very common thing, and recently Unity added full support for Linux. I've been using it for a while now and it's great, but this minor aseprite issue hurts my workflow.

I really wish I could contribute, but I have no clue on how any of this code works. First thing that came to my mind was making a bash script that checks for an existing aseprite process, and somehow sending the message to open an image to that process, but I also don't know if that's possible.

**Comment by dacap** [comment]
@henriquecolini a solution for all platforms would be to use named pipes, it's something I'd like to add in a near future, but if you want to give a try you can go for it (we'll need a way to handle named pipes from the laf library first).

**Comment by nazgum** [comment]
For any other Linux users struggling with this, I created a workaround that makes Aseprite always opens files in the same window.  I'm currently using this, and hope it might help someone else on linux til aseprite can get it added =)

https://abitawake.com/news/articles/make-aseprite-always-open-files-in-the-same-window-on-linux

Cheers,

**Comment by Haelle** [comment]
> For any other Linux users struggling with this, I created a workaround that makes Aseprite always opens files in the same window. I'm currently using this, and hope it might help someone else on linux til aseprite can get it added =)
> 
> https://abitawake.com/news/articles/make-aseprite-always-open-files-in-the-same-window-on-linux
> 
> Cheers,

Nice hack, I tried something like that but your solution is better !

I made some few changes to make it work on Ubuntu : https://gist.github.com/Haelle/c2de432e1d5ad3af3fd36831d5a501ef

however I have a strange behavior on the second tab to open I have to paste manually but for the following files it's working.
It's good enough for me so I didn't investigate more.

**Comment by henriquecolini** [comment]
So... has there been any progress in this, or perhaps named pipes 😅 ? I'd implement that myself, but the codebase is a bit overwhelming, I don't know even where to start. It's been like 11 years since the feature request... sorry for bothering, @dacap

**Comment by dacap** [comment]
@henriquecolini this feature works on Windows using DDE and on macOS is integrated. We'd require something for Linux and that is low priority (when some extra work has to be done specially for Linux, generally it's quite low priority, given the low number of users we have on Linux and the amount of work on Windows/macOS).

**Comment by henriquecolini** [comment]
@dacap Thanks for the quick response! Yes, that is perfectly understandable.

I spent a few hours trying to understand the codebase, and... I might _actually_ be able to implement this feature. I saw the way it was done in Windows (simply emulating a `Event::DropFiles` event in laf), and did something similar in `EventQueueX11::getEvent(Event& ev, double timeout)` with non blocking named pipe... and it worked! By echoing file paths to that pipe, aseprite actually opens them. That was easier than I thought.

```c++
if (pipe_fd != -1) {
char buf[4096];
ssize_t n = read(pipe_fd, buf, sizeof(buf) - 1);
if (n > 0) {
  buf[n] = 0;
  std::vector<std::string> files;
  std::istringstream iss(buf);
  std::string line;
  while (std::getline(iss, line)) {
    if (!line.empty())
      files.push_back(line);
  }
  if (!files.empty()) {
    Event dropEv;
    dropEv.setType(Event::DropFiles);
    dropEv.setFiles(files);
    os::queue_event(dropEv);
  }
}
```

I don't know if this is the correct way to do it, but at least it seems to work without issues. Now I need to figure out how to check if an instance of aseprite is already running and actually write the file paths to that pipe. Should be straight forward...

Oh, and, while we're at it, which branch should I be using for laf and aseprite?

**Comment by lajawi** [comment]
> this feature works on Windows

This should already work on Windows? Then I think my install is somehow slightly off, I did have to fix the registry entries manually to make the file associations work again, maybe that broke this (or never fixed it).

How should I check my install is set up correctly for this to work? Is there maybe a button that fixes the registry automatically?

**Comment by andersmmg** [comment]
@henriquecolini Could you share where you implemented this change? I'm interested in trying it out locally

**Comment by henriquecolini** [comment]
@andersmmg I'm yet to make a PR following the correct guidelines, but these are the changes (needs a change in laf and aseprite)

https://github.com/aseprite/aseprite/compare/main...henriquecolini:aseprite:main

https://github.com/aseprite/laf/compare/main...henriquecolini:laf:main

**Comment by IntangibleMatter** [comment]
Just was running into this issue myself, glad to see it looks like someone is working on progress for this issue! I hope it gets implemented sometime soon :)

**Comment by feeeedox** [comment]
Hi, any progress?
